# Generated by Django 4.1.5 on 2023-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=500)),
                ("bname", models.CharField(max_length=500)),
                ("ispic", models.IntegerField()),
                ("bpic", models.CharField(blank=True, max_length=1000, null=True)),
                ("bcategory", models.CharField(max_length=500)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                ("payment", models.CharField(max_length=500)),
                ("amount", models.IntegerField()),
                ("btime", models.DateTimeField()),
                ("isreceipt", models.IntegerField()),
                ("receipt", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "db_table": "ins",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Outs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=500)),
                ("bname", models.CharField(max_length=500)),
                ("ispic", models.IntegerField()),
                ("bpic", models.CharField(blank=True, max_length=1000, null=True)),
                ("isfinish", models.IntegerField()),
                ("isremind", models.IntegerField()),
                ("rtime", models.DateTimeField(blank=True, null=True)),
                ("bcategory", models.CharField(max_length=500)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                ("payment", models.CharField(max_length=500)),
                ("amount", models.IntegerField()),
                ("btime", models.DateTimeField()),
                ("isreceipt", models.IntegerField()),
                ("receipt", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "db_table": "outs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usersinfo",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("iswx", models.IntegerField()),
                ("wxid", models.CharField(blank=True, max_length=500, null=True)),
                ("iszfb", models.IntegerField()),
                ("zfbid", models.CharField(blank=True, max_length=500, null=True)),
                ("uname", models.CharField(max_length=500)),
                ("uphone", models.CharField(max_length=20)),
                ("ubirth", models.DateField()),
                ("password", models.CharField(max_length=45)),
                ("upic", models.CharField(max_length=1000)),
                ("ucreate", models.DateField()),
            ],
            options={
                "db_table": "usersinfo",
                "managed": False,
            },
        ),
    ]
