# Generated by Django 4.1.5 on 2023-03-05 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0002_alter_ins_bpic_alter_outs_bpic_alter_usr_upic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usr",
            name="ucreate",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
