# Generated by Django 4.1.5 on 2023-03-09 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0003_alter_usr_ucreate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ins",
            name="isreceipt",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="usr",
            name="ucreate",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
