# Generated by Django 4.1.5 on 2023-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0004_alter_ins_isreceipt_alter_usr_ucreate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outs",
            name="bname",
            field=models.CharField(
                blank=True, default="defaut-user-name", max_length=500
            ),
        ),
    ]
