# Generated by Django 4.1.5 on 2023-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0005_alter_outs_bname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outs",
            name="isfinish",
            field=models.BooleanField(default=True),
        ),
    ]
