# Generated by Django 4.1.5 on 2023-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0007_ins_id_alter_ins_btime_alter_outs_id_alter_usr_iswx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ins",
            name="bpic",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ins",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, verbose_name="自增id"
            ),
        ),
        migrations.AlterField(
            model_name="ins",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ins",
            name="receipt",
            field=models.CharField(
                blank=True, db_index=True, max_length=300, null=True
            ),
        ),
        migrations.AlterField(
            model_name="outs",
            name="bpic",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="outs",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, verbose_name="自增id"
            ),
        ),
        migrations.AlterField(
            model_name="outs",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="outs",
            name="receipt",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="usr",
            name="upic",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
