# Generated by Django 4.1.5 on 2023-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0008_alter_ins_bpic_alter_ins_id_alter_ins_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usr",
            name="upic",
            field=models.CharField(
                blank=True,
                default="static/a37/avatar_images/default.png",
                max_length=500,
                null=True,
            ),
        ),
    ]
