# Generated by Django 4.1.5 on 2023-05-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0009_alter_usr_upic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_num", models.IntegerField(primary_key=True, serialize=False)),
                ("context", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Own",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=500)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="A37.room"
                    ),
                ),
                (
                    "usr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="A37.usr"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                ("role", models.CharField(max_length=500)),
                ("time", models.DateField()),
                ("amount", models.FloatField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="A37.room"
                    ),
                ),
            ],
        ),
    ]
