# Generated by Django 4.1.5 on 2023-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0010_room_own_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="pwd",
            field=models.CharField(default="123456", max_length=500),
        ),
    ]
