# Generated by Django 4.1.5 on 2023-05-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0012_alter_own_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="role",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="own",
            name="role",
        ),
    ]
