# Generated by Django 4.1.5 on 2023-05-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0013_rename_role_info_comment_remove_own_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="time",
            new_name="bime",
        ),
    ]
