# Generated by Django 4.1.5 on 2023-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A37", "0014_rename_time_info_bime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="bime",
            new_name="btime",
        ),
    ]
